lib/core/src/display/rendering/camera.rs, lib/core/src/display/rendering/htmlobject.rs, lib/core/src/display/rendering/htmlrenderer.rs, lib/core/src/display/rendering/htmlscene.rs, lib/core/src/display/rendering/object.rs, lib/core/src/display/rendering/renderer.rs, lib/core/src/display/rendering/scene.rs, lib/core/src/display/rendering/transform.rs
=> Refactoring

docs/style-guide.md
=> Rust code style guide

lib/core/src/text.rs, lib/core/src/text/buffer.rs, lib/core/src/text/buffer/fragment.rs, lib/core/src/text/buffer/glyph_square.rs, lib/core/src/text/content.rs, lib/core/src/text/msdf_vert.glsl, lib/core/tests/text.rs
Added operation for editing text in text component, which does the minimal required buffer refresh.
=> Text editing

script/build.sh
The build script got accidentally broken in #128 (clion refactored too much).
This fixes accidental core->impl replacement.
=> Fix build.sh

src/js/lib/client/package.js, src/js/lib/client/src/index.js, src/js/lib/content/src/index.html, src/js/lib/icons/src/index.js, src/js/package-lock.json
- Fixes [Icon on MacOs is too big](https://github.com/luna/ide/issues/249)
- Fixes [Enso Studio icon not visible in macOS finder](https://github.com/luna/ide/issues/248)
- Hopefully fixes [Can't run the build artifact](https://github.com/luna/ide/issues/257)
- Provides more info about [It is not possible to rescale Enso Studio window with top window edge](https://github.com/luna/ide/issues/243) CC @sylwiabr 
- Provides more info about [Enso Studio edges and corners looks different then edges of the rest MacOS applications](https://github.com/luna/ide/issues/253) CC @sylwiabr 
**WARNING this PR removes ability to drag the app in order to check if it was a cause of badly drawn corners. It will be re-enabled in the future**
=> Improving Electron App

src/rust/ide/src/controller/module.rs
=> Removes idmap field from module controller.

src/rust/Cargo.lock, src/rust/ide/Cargo.toml, src/rust/ide/src/controller/graph.rs, src/rust/ide/src/controller/module.rs
Implements modification of node position in metadata.
=> Graph API - Node position in metadata

docs/contributing.md
Update instructions for the toolchain setup in the contributor guidelines. 
This fixes #283 and makes the toolchain setup project-specific. That means, following these instructions will not affect the toolchains used in other projects on the same system and allows using different nightly versions for different projects.
=> Fix instructions to set up toolchain for project build. Fixes #283.

src/rust/lib/shapely/impl/tests/derive_clone_ref.rs, src/rust/lib/shapely/macros/src/derive_clone_ref.rs
=> Fix #[derive(CloneRef)] for generic types with more than one type parameter.

README.md, docs/contributing.md
This PR is part of my updates of the main repositories to reflect the new `enso.org` domain.
An additional section was added to contributing.
=> Update Documentation to Refer to New Domain

src/rust/ide/ast/impl/src/crumbs.rs, src/rust/ide/ast/impl/src/lib.rs, src/rust/ide/ast/impl/src/repr.rs, src/rust/ide/parser/tests/crumbs.rs, src/rust/ide/parser/tests/parsing.rs, src/rust/ide/span-tree/src/node.rs, src/rust/ide/src/double_representation/alias_analysis.rs, src/rust/ide/src/double_representation/definition.rs
=> Crumb implementation for Match and Ambiguous.

src/rust/ensogl/src/display/shape/text/glyph/system.rs, src/rust/ide/src/view/node_editor.rs, src/rust/lib/logger/src/lib.rs
This fixes two crashes which occurs or may occur during IDE startup
1. The shader which is not compiling
2. Crash when editing text and there is no main function
=> Fix crashes on IDE startup

src/rust/Cargo.lock, src/rust/lib/graph-editor/Cargo.toml, src/rust/lib/graph-editor/src/component/node.rs, src/rust/lib/graph-editor/src/lib.rs
This PR contains the definition of endpoints which IDE will require to work properly with GraphEditor. They're not used yet, nor they have any implementation.
Of course the exact shape may be changed, but this shoud show IDE requirements.
=> Add endpoints to GraphEditor

src/rust/ide/enso-protocol/src/project_manager.rs, src/rust/ide/src/lib.rs
Applies rename in protocol from https://github.com/luna/enso/commit/7d82b1abee0f20b87b578c9ddd1a7f11330b9738#diff-4016bb70804aef56e4cc9b27e81a8322L853
=> Update Engine API

src/js/package-lock.json, src/rust/Cargo.toml, src/rust/ensogl/msdf-sys/src/lib.rs, src/rust/ensogl/src/display/scene.rs, src/rust/ensogl/src/display/shape/text/glyph/font.rs, src/rust/ensogl/src/display/shape/text/glyph/pen.rs, src/rust/ensogl/src/display/shape/text/glyph/system.rs, src/rust/ensogl/src/display/shape/text/text_field.rs, src/rust/ensogl/src/display/shape/text/text_field/content.rs, src/rust/ensogl/src/display/shape/text/text_field/content/line.rs, src/rust/ensogl/src/display/shape/text/text_field/cursor.rs, src/rust/ensogl/src/display/shape/text/text_field/render.rs, src/rust/ensogl/src/display/shape/text/text_field/render/assignment.rs, src/rust/ensogl/src/display/world.rs, src/rust/ide/parser/tests/web.rs, src/rust/ide/src/view/layout.rs, src/rust/ide/src/view/node_searcher.rs, src/rust/ide/src/view/project.rs, src/rust/ide/src/view/text_editor.rs, src/rust/lib/debug-scenes/src/glyph_system.rs, src/rust/lib/debug-scenes/src/shapes.rs, src/rust/lib/debug-scenes/src/text_field.rs, src/rust/lib/debug-scenes/src/text_typing.rs, src/rust/lib/graph-editor/src/component/connection.rs, src/rust/lib/graph-editor/src/component/node.rs, src/rust/lib/graph-editor/src/component/node/port.rs, src/rust/lib/graph-editor/src/lib.rs
Implements https://github.com/luna/ide/issues/440
Please take into consideration that most changes in this PR are in the WIP-files. So not everything is as beautiful as it should be. Nodes, connections, graph editor implementations will be cleaned up gradually in the next PRs.
=> Ability to change text on nodes.

src/js/package-lock.json, src/rust/Cargo.toml, src/rust/ensogl/src/data/dirty.rs, src/rust/ensogl/src/display/object/class.rs, src/rust/ensogl/src/display/scene.rs, src/rust/ensogl/src/display/shape/text/text_field/content.rs, src/rust/ensogl/src/gui/component.rs, src/rust/lib/debug-scenes/src/shapes.rs, src/rust/lib/frp/src/macros.rs, src/rust/lib/graph-editor/src/component/connection.rs, src/rust/lib/graph-editor/src/component/node.rs, src/rust/lib/graph-editor/src/component/node/port.rs, src/rust/lib/graph-editor/src/lib.rs
- Fixing bug with connections not synced with mouse.
- Fixing bug with mouse frozen after selected element is removed.
- Fixing bug with invisible nodes after pressing "n".
=> Graph Editor bug fixes

src/rust/ide/ast/impl/src/lib.rs, src/rust/ide/ast/impl/src/repr.rs, src/rust/ide/parser/tests/parsing.rs, src/rust/lib/system/web/src/lib.rs
Uses the same implementation as scala parser.
=> Fix repr of block for empty lines.

src/js/package-lock.json, src/rust/Cargo.toml, src/rust/ensogl/src/animation/easing.rs, src/rust/ensogl/src/animation/physics/inertia.rs, src/rust/ensogl/src/data/color/data.rs, src/rust/ensogl/src/display/camera/camera2d.rs, src/rust/ensogl/src/display/scene.rs, src/rust/ensogl/src/gui/component.rs, src/rust/ensogl/src/lib.rs, src/rust/ensogl/src/math/algebra.rs, src/rust/lib/debug-scenes/src/easing_animator.rs, src/rust/lib/graph-editor/src/component/cursor.rs, src/rust/lib/graph-editor/src/component/edge.rs, src/rust/lib/graph-editor/src/component/node.rs, src/rust/lib/graph-editor/src/component/node/port.rs, src/rust/lib/graph-editor/src/lib.rs
- Implements [Mouse port selection not working after scene pan](https://github.com/luna/ide/issues/465)
=> Mouse port selection not working after scene pan

src/rust/ide/src/controller/visualization.rs, src/rust/lib/graph-editor/src/builtin/visualization/java_script.rs, src/rust/lib/graph-editor/src/component/visualization/data.rs, src/rust/lib/graph-editor/src/component/visualization/definition.rs, src/rust/lib/graph-editor/src/component/visualization/foreign/java_script/definition.rs, src/rust/lib/graph-editor/src/component/visualization/foreign/java_script/instance.rs, src/rust/lib/graph-editor/src/component/visualization/instance.rs, src/rust/lib/graph-editor/src/component/visualization/registry.rs
Fix the FIXME's and TODO's left in the PR.
Touches some code in the tests from the controller, too.
=> Visualisation FIXMEs

run
This ensures that the expected node version number shows up in the error message.
=> Ensure the `node` is checked first.

src/rust/lib/graph-editor/src/lib.rs
Enable multi-select iff cmd is held down during selection.
Re-uses same command from node-multi select. 
=> Edge multi select

src/rust/ensogl/src/display/scene.rs, src/rust/lib/graph-editor/src/lib.rs
Fixed edges getting desynchronized when panning / zooming scene during edge connection.
=> Use correct position to calculate edge dragging.

src/rust/ide/src/double_representation/text.rs
I made a mistake when previously refactoring this.
This PR fixes the code and also improves behavior in few other cases.
Tests included.
=> Fixed a few cases for id map updating by text API.

src/rust/Cargo.lock, src/rust/ide/lib/view/Cargo.toml, src/rust/ide/lib/view/src/graph_editor.rs, src/rust/ide/src/controller/graph/executed.rs, src/rust/ide/src/controller/project.rs, src/rust/ide/src/model/execution_context.rs, src/rust/ide/src/view/node_editor.rs
Similarly to what we do with type information, this PR also adds passing the method pointer information to the graph editor view.
=> Pass the method pointers information to the graph editor.

build/run.js, src/rust/ide/lib/enso-protocol/src/language_server.rs, src/rust/ide/lib/enso-protocol/src/language_server/response.rs, src/rust/ide/lib/enso-protocol/src/language_server/tests.rs, src/rust/ide/lib/enso-protocol/src/language_server/types.rs, src/rust/ide/lib/enso-protocol/src/project_manager.rs, src/rust/ide/lib/json-rpc/src/macros.rs, src/rust/ide/src/controller.rs, src/rust/ide/src/controller/graph.rs, src/rust/ide/src/controller/graph/executed.rs, src/rust/ide/src/controller/module.rs, src/rust/ide/src/controller/text.rs, src/rust/ide/src/ide.rs, src/rust/ide/src/model.rs, src/rust/ide/src/model/execution_context.rs, src/rust/ide/src/model/module.rs, src/rust/ide/src/model/project.rs, src/rust/ide/src/model/registry.rs, src/rust/ide/src/model/suggestion_database.rs, src/rust/ide/src/model/synchronized/module.rs, src/rust/ide/src/view/layout.rs, src/rust/ide/src/view/node_editor.rs, src/rust/ide/src/view/project.rs, src/rust/ide/tests/language_server.rs
This PR contains both methods for LS client for suggestions as well as the database struct available in Project Model which is kept up to date. Also refactored a bit the models and controllers.
=> Suggestions Database

src/rust/ensogl/src/display/camera/camera2d.rs
This PR provides a hotfix for the issue causing scene to be culled out of the view frustum.
=> Camera zfar hotfix

src/rust/Cargo.lock, src/rust/ide/Cargo.toml, src/rust/ide/lib/ast/impl/src/known.rs, src/rust/ide/lib/ast/impl/src/lib.rs, src/rust/ide/lib/ast/impl/src/macros.rs, src/rust/ide/lib/ast/impl/src/repr.rs, src/rust/ide/lib/parser/tests/macros.rs, src/rust/ide/lib/parser/tests/parsing.rs, src/rust/ide/src/controller/module.rs, src/rust/ide/src/controller/project.rs, src/rust/ide/src/double_representation/module.rs, src/rust/ide/src/model/module.rs, src/rust/ide/src/model/synchronized/execution_context.rs, src/rust/ide/src/view/node_editor.rs
This PR adds helper methods to manage imports in the module.
=> Import Management

build/run.js, docs/CONTRIBUTING.md, docs/README.md, docs/product/README.md, docs/product/searcher.md, docs/repository-structure.md, src/rust/ide/src/controller.rs, src/rust/ide/src/controller/searcher.rs, src/rust/ide/src/model/module.rs, src/rust/ide/src/model/suggestion_database.rs, src/rust/ide/src/view/layout.rs, src/rust/ide/src/view/node_editor.rs, src/rust/ide/src/view/node_searcher.rs
This PR introduces a new controller for the Searcher. Currently it loads and provides an initial list of suggestions. Additionally there is a raw integration with view: then the current Searcher is put into the screen, it logs all the suggestions retrieved from the Engine. 
Currently the logs always show empty list, because Engine does not have implementation of the API yet.
=> Searcher Controller

src/rust/ide/lib/ast/impl/src/prefix.rs, src/rust/ide/lib/parser/tests/ast.rs, src/rust/ide/src/controller/searcher.rs, src/rust/ide/src/double_representation/module.rs, src/rust/ide/src/model/module.rs, src/rust/ide/src/model/suggestion_database.rs, src/rust/ide/src/view/node_editor.rs, src/rust/lib/data/src/text.rs
This PR implements the function for applying suggestion by user in the Searcher Controller (the action on "Tab"). It also contains a bit of the controller refactoring.
=> Applying suggestion in Searcher

build/run.js, src/rust/ide/lib/enso-protocol/src/language_server/types.rs, src/rust/ide/src/model/project.rs
Previously the `executionContext/executionFailed` notification wasn't correctly serialized, leading to deserialization errors in logs.
Now it is deserialized and lead to logging proper errors, as reported by the language server.
=> Deserialization of the `executionContext/executionFailed` notification.

src/rust/ide/lib/parser/build.rs, src/rust/ide/lib/parser/src/jsclient.rs, src/rust/ide/lib/parser/src/lib.rs, src/rust/ide/lib/parser/src/main.rs, src/rust/ide/lib/parser/src/wsclient.rs, src/rust/ide/lib/parser/tests/doc-gen.rs
Waiting for unblock from @mwu-tow
This PR introduces connection between websocket parser-service and JS-compiled scala documentation parser and html generator for IDE
=> Connect Doc Parser and generator to IDE

src/rust/ide/lib/enso-protocol/src/language_server.rs, src/rust/ide/lib/enso-protocol/src/language_server/types.rs, src/rust/ide/src/constants.rs, src/rust/ide/src/controller/searcher.rs, src/rust/ide/src/double_representation/graph.rs, src/rust/ide/src/model/project/synchronized.rs, src/rust/ide/src/model/suggestion_database.rs
This PR fixes all discrepancies between IDE and Engine since Engine delivered implementation of suggestions.
=> Suggestions fixes

build/run.js, src/rust/ide/lib/ast/impl/src/identifier.rs, src/rust/ide/lib/enso-protocol/src/language_server/types.rs, src/rust/ide/lib/span-tree/src/node.rs, src/rust/ide/lib/utils/src/future.rs, src/rust/ide/lib/utils/src/lib.rs, src/rust/ide/lib/view/src/graph_editor.rs, src/rust/ide/src/controller/graph.rs, src/rust/ide/src/controller/graph/executed.rs, src/rust/ide/src/controller/searcher.rs, src/rust/ide/src/executor/test_utils.rs, src/rust/ide/src/lib.rs, src/rust/ide/src/model/execution_context.rs, src/rust/ide/src/model/execution_context/plain.rs, src/rust/ide/src/model/execution_context/synchronized.rs, src/rust/ide/src/model/suggestion_database.rs, src/rust/ide/src/test.rs, src/rust/ide/src/view/node_editor.rs, src/rust/ide/src/view/node_searcher.rs, src/rust/lib/enso-prelude/src/option.rs
Bringing searcher with node selected will use this node as a "this" argument for the function selected by the user.
=> Searcher Controller with "this"

src/rust/ide/lib/view/src/debug_scenes/shapes.rs
Add facilities to compute colors from types (basic hashing and mapping algorithm) as well as facilities to color edges, ports and the cursor dependent on their respective types. 
Does not enforce correct connections. Of two different colored ports are connected, one color will be used for the edge.
Known Issue: `text::Area` changes the cursor on hover internally, and thus cancels the color of the cursor if it was dragging a typed edge. The ``text::Area` should be refactored to emit an event instead, that can be used in the `GraphEditor` to implement the correct behavior. The correct behavior is most likely to not allow changing the cursor while it is dragging an edge. 
=>  Ability to set edge color based on type.

src/rust/ide/src/view/project.rs
This addresses #510 by recreating the file if it is missing.
This fix should be treated as provisional. The shape of the final one depends on the discussion from https://github.com/enso-org/enso/issues/1050
=> Recreate Main.enso file if it is missing.

.github/workflows/check.yml
fixes #704
We've found the problem with @mwu-tow, here comes the fix
=> Disable caching to fix CI

src/rust/ide/src/view/project.rs
The IDE won't make the necessary setup for zooming and panning.
=> Fix zooming and panning in IDE.

src/js/package-lock.json, src/rust/ensogl/lib/core/src/system/gpu/data/attribute.rs, src/rust/ensogl/lib/core/src/system/gpu/data/buffer.rs, src/rust/ensogl/lib/core/src/system/gpu/data/buffer/item.rs, src/rust/ensogl/lib/core/src/system/gpu/data/default.rs
- Implements (Fix old visual elements state. After selected node is removed and new is created, it looks like it was already selected.)[https://github.com/enso-org/ide/issues/464]
- Refactors some doc comments 
=> Fixing the bug: Fix old visual elements state. 

src/rust/ide/src/view/node_editor.rs
=> Fix nodes overlapping

src/js/lib/client/src/index.js, src/js/lib/client/src/preload.js
This PR fixes :
#247 - transparency of window.
#484 - moving window was really hard because of lack of frame.
#743 - window controls covered the project name. Now as the frame is reintroduced to the window, controls are part of it, and they don't overlap the scene.
=> Fix electron-related bugs

build/run.js, src/rust/Cargo.lock, src/rust/ide/Cargo.toml, src/rust/ide/src/lib.rs
Enabled EnsoGL examples in IDE package.
=> Enable EnsoGL examples in IDE

docs/product/shortcuts.md, src/js/lib/client/src/index.js
=> Fix ability to toggle dev console in app.

.github/CODEOWNERS
Restoring the old codeowners, as they returned from vacation.
=> Restore codeowners

src/rust/Cargo.toml, src/rust/ide/view/graph-editor/src/component/visualization/instance.rs, src/rust/lib/enso-prelude/src/lib.rs, src/rust/lib/enso-prelude/src/vec.rs, src/rust/lib/shortcuts/example/src/lib.rs, src/rust/lib/shortcuts/src/lib.rs
=> Fixing sticky keys bug

docs/product/shortcuts.md
=> Add missing shortcut to docs

src/js/package-lock.json, src/rust/ensogl/lib/core/src/control/io/mouse.rs, src/rust/ensogl/lib/core/src/control/io/mouse/event.rs, src/rust/ensogl/lib/core/src/display/scene.rs, src/rust/ide/view/graph-editor/src/component/visualization/foreign/java_script/instance.rs, src/rust/ide/view/src/debug_scenes/visualization.rs, src/rust/lib/frp/src/io.rs, src/rust/lib/frp/src/io/js.rs, src/rust/lib/frp/src/io/keyboard.rs, src/rust/lib/shortcuts/example/src/lib.rs
Make keyboard events managing being analogous as mouse events.
* Some parts of frp::io::keyboard were moved to new "js" module which should have all commons for both mouse and keyboard management.
* Also logic for passing or not a js event to DOM was moved there
* Fixed the outdated visualization example.
=> Visualization active state for keyboard events

src/rust/ide/view/graph-editor/src/lib.rs
Implement the "connection removed" event properly.
=> Fix disconnecting

src/rust/ide/view/graph-editor/src/lib.rs
This fixes the bug where node were left after removing/collapsing
=> Fix node view leaking

build/run.js, src/rust/ensogl/lib/core/src/data/color/animation.rs, src/rust/ide/view/graph-editor/src/lib.rs
Emit appropriate signal from GraphEditor when user click on "eye" icon on node.
=> Fix visualization show action

src/rust/ide/view/graph-editor/src/lib.rs
This PR adds an edge position refres to edges connected to a node after the node has received a new expression.
This ensures that after an expression update, already connected edges are positioned correclty. This is relevant in some situations, where expression changes partially, and existing edges stay in place without beeind re-created.
=> PR: Connector position does not change if node size changes on connection

src/rust/ide/src/constants.rs
Update expression to the newest engine changes.
=> Fix visualization expression.

src/rust/ide/view/src/documentation/style.css
Quickfix after change I was supposed to merge but didnt...
=> Fix the code block not showing in documentation view.

src/js/package-lock.json, src/rust/ide/view/graph-editor/src/component/visualization/foreign/java_script/instance.rs, src/rust/ide/view/graph-editor/src/component/visualization/instance.rs, src/rust/ide/view/src/documentation.rs, src/rust/lib/frp/src/io/js.rs
Documentation panel may active similarly to visualizations; being active it receives mouse and keyboard events.
* Mouse pointer is still under the documentation panel. This can be fixed only by providing way of "cutting webgl canvas"
* The copying with Ctrl+C is overridden by same shortcut in searcher input. It can be fixed by hierarchical event handling.
=> Documentation Event Handling.

.github/PULL_REQUEST_TEMPLATE.md
Add notes about manual testing to our PR template.
=> Add requirement for verifying test scenarios to PR template.

build/run.js, docs/CONTRIBUTING.md, src/rust/Cargo.toml, src/rust/ide/lib/enso-protocol/src/language_server/types.rs, src/rust/ide/src/controller/searcher.rs, src/rust/ide/src/model/execution_context.rs, src/rust/ide/src/model/execution_context/plain.rs, src/rust/ide/src/model/suggestion_database.rs, src/rust/ide/src/test.rs
This PR updates the IDE application to understand new changes in suggestion database Engine API.
As usual, the new structures in `language_server::types` reflects the engine api, however the API is in some places badly designed. I will create an issue for Engine to improve that, but after the first release.
=> Engine API update

src/js/lib/common/src/loader.js, src/rust/ensogl/lib/theme/src/lib.rs, src/rust/ide/lib/enso-protocol/src/handler.rs, src/rust/ide/lib/enso-protocol/src/lib.rs, src/rust/ide/lib/span-tree/src/generate.rs, src/rust/ide/src/lib.rs, src/rust/ide/src/view/integration.rs, src/rust/ide/view/graph-editor/src/component/node.rs, src/rust/ide/view/graph-editor/src/component/node/expression.rs, src/rust/ide/view/graph-editor/src/component/node/input/area.rs, src/rust/ide/view/graph-editor/src/component/node/input/port.rs, src/rust/ide/view/graph-editor/src/lib.rs
=> Improving port highlighting

src/rust/ensogl/lib/core/src/display/scene.rs
Fixes accidentally broken tests on main.
=> Fixing tests

src/js/lib/content/src/index.html
After some merges visualization corner radius has been lost, this pr restores it.
=> Fix visualization border radius.

src/js/lib/client/package.js, src/js/package-lock.json
Bumped electron version addressing the github security alert.
=> Bump electron version

src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/histogram.js, src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/scatterPlot.js
Enables scatter plots and histogram plots to consume bare vectors as input as opposed to the structured JSON inputs that is generally expected. 
This is a workaround that should go away with the implementation of DataFrames. There is a tracking issue for the that is referred to in the code here https://github.com/enso-org/ide/issues/1006 and this should be cleaned up when DataFrames are integrated. 
=> Allow visualizations to consume bare vectors

src/rust/ide/src/view/integration.rs
Enables the default position of a node to be written to its metadata. 
=> Set a node's position to the default value in the metadata if there is not any.

build/run.js, src/rust/ensogl/lib/text/src/component/area.rs
Applies #934 
Adds cmd-x shortcut to text area.
=> Cut shortcut for text area.

docs/CONTRIBUTING.md, src/rust/ide/lib/enso-protocol/src/project_manager.rs, src/rust/ide/src/controller/graph/executed.rs, src/rust/ide/src/ide.rs, src/rust/ide/tests/project_manager.rs
At some point Project Manager requires special flag to download and install engine components.
=> Install missing components of Engine

src/rust/ide/src/ide.rs
A temporary solution for handling long Engine download.
=> Increase PM timeout

src/rust/ensogl/example/src/list_view.rs, src/rust/ensogl/lib/theme/src/lib.rs, src/rust/ide/view/src/project.rs
=> Refactoring theme management

src/rust/ide/lib/enso-protocol/src/language_server/types.rs, src/rust/ide/lib/utils/src/lib.rs, src/rust/ide/lib/utils/src/string.rs, src/rust/ide/src/model/module/synchronized.rs
Adds a high-level optimization to limit changes sent out to the engine. This is achieved by applying a pre- and postfix trimming to source code changes.
=> Optimised engine updates

.github/workflows/build.yml, build/paths.js, build/run.js, src/js/lib/client/package.js, src/js/lib/client/src/index.js, src/js/lib/project-manager/package.js, src/js/lib/project-manager/src/build.ts, src/js/package-lock.json
Add a fixed version of the project manager to our build. 
Needs to be updates from time to time to use a newer version of the project manager. Build artefacts should be tested on all platforms. 
=> Bundle project manager in electron package. 

src/js/lib/client/src/index.js, src/rust/ide/view/graph-editor/src/lib.rs
=> Fixing node multi-select, adding electron options

src/js/lib/client/src/index.js, src/js/lib/project-manager/src/build.ts, src/js/package-lock.json
Adding backend version info to the electron app.
=> Adding backend version info to the electron app.

src/js/lib/project-manager/src/build.ts, src/js/package-lock.json
Make IDE use the Project Manager from the official Enso release 0.2.0
=> Bump ProjectManager version

src/rust/ide/lib/ast/impl/src/test_utils.rs, src/rust/ide/lib/parser/tests/parsing.rs, src/rust/ide/view/graph-editor/src/component/node/output/area.rs, src/rust/ide/view/graph-editor/src/lib.rs
Update the output root type id if the whole node's expression type has changed.
=> Fix output edge coloring

.github/workflows/build.yml, .github/workflows/check.yml, .github/workflows/release.yml, docs/CONTRIBUTING.md
Upgrade wasm-pack from 0.8.1 to 0.9.1. This avoids 0.8.1 no longer building on our compiler version. 
We should probably soon upgrade our compiler version. 
=> Upgrade wasm pack from 0.8.1 to 0.9.1.

.github/workflows/build.yml
=> Fixing wasm-pack build

.github/workflows/build.yml, package-lock.json, src/js/lib/content/package.js, src/js/lib/content/src/index.js, src/js/package-lock.json, src/rust/Cargo.lock, src/rust/ide/Cargo.toml, src/rust/ide/lib/analytics/Cargo.toml, src/rust/ide/lib/analytics/src/data.rs, src/rust/ide/lib/analytics/src/lib.rs, src/rust/ide/lib/analytics/src/remote_log.rs, src/rust/ide/src/ide/integration.rs, src/rust/ide/view/graph-editor/Cargo.toml, src/rust/ide/view/graph-editor/src/component/visualization/container/visualization_chooser.rs
=> Implement remote logging.

src/rust/ide/src/controller/graph.rs, src/rust/ide/src/ide/integration.rs, src/rust/ide/view/graph-editor/src/component/visualization/container/visualization_chooser.rs
Better events to track node editing and node entering/leaving. 
=> Update to logging.

src/rust/ide/lib/analytics/src/remote_log.rs
=> Fix test regression introduced by remote logging.
