enso-org/ide

lib/core/src/lib.rs, lib/core/src/text.rs, lib/core/src/text/buffer.rs, lib/core/src/text/buffer/fragment.rs, lib/core/src/text/buffer/glyph_square.rs, lib/core/src/text/msdf_frag.glsl, lib/core/src/text/msdf_vert.glsl
Text in text component is clipped to specified area on screen. Only visible part of text have its data in opengl buffers. The buffer management was somewhat adapted to quick scrolling with minimum buffer data refreshing.
=> Text clipping

.github/workflows/build.yml, script/test.sh
Running web tests in Chrome sometimes gets stuck with a message `Loading scripts...`. This PR switches the browser of choice for our web tests from Chrome to Firefox.
=> Using Firefox for headless web tests

lib/core/src/display/shape/text/text_field.rs, lib/core/src/display/shape/text/text_field/content.rs, lib/core/src/display/shape/text/text_field/cursor.rs, lib/core/src/display/shape/text/text_field/location.rs, lib/core/src/display/shape/text/text_field/render/selection.rs, lib/core/src/examples/text_selecting.rs
Before, all edits did not adjust the cursor positions, but they remained with their selection in the same location. This PR changes that.
=> Moving cursors after each edit

lib/ide/file-manager/mock-server/Cargo.toml, lib/ide/file-manager/mock-server/README.md, lib/ide/file-manager/mock-server/src/main.rs
A few fixes and improvements for FM mock server:
* it used wrong function to serialize JSON reply
* now it prints messages on stdout, making debugging of the client much easier
* added two more functions to have more fun when testing integration
This is a throwaway code used only to facilitate development of #143 and presentation of milestone 0.
It will be removed when cloud provides their implementation.
=> Fixes and Improvements for File Manager Mock Server

lib/ide/file-manager/README.md, lib/ide/file-manager/src/lib.rs, lib/ide/json-rpc/src/messages.rs
For some reason when implementing JSON-RPC I used `input` instead of `params` (as specified).
This PR fixes this.
=> JSON-RPC uses `params`, not `input`

lib/core/src/display/shape/text/glyph/system.rs, lib/core/src/display/symbol/geometry/compound/sprite.rs
Previously when running examples, the text and sprites were not visible on my machine (Windows, Chrome). This PR, thanks to @wdanilo, fixes the issue.
=> Fixes for Rendering on Windows

.github/workflows/build.yml, build/run.js, src/rust/Cargo.toml
- Runs tests only on MacOS, which is fastest setup on GH Actions + saves the actions instances so we dont run out of its limits and dont get queued.
- Runs native and WASM tests in parallel to save the time.
=> Making tests on CI faster by running them in parallel

src/js/package-lock.json, src/rust/ensogl/src/display/object.rs, src/rust/ensogl/src/display/shape/text/text_field.rs, src/rust/ensogl/src/display/shape/text/text_field/render.rs, src/rust/ensogl/src/display/symbol/gpu/geometry/compound/sprite.rs, src/rust/ide/src/view/text_editor.rs, src/rust/lib/debug-scenes/src/sprite_system.rs, src/rust/lib/debug-scenes/src/text_field.rs, src/rust/lib/debug-scenes/src/text_typing.rs
This code fixes the problem with text selection which occurs after recent DisplayObject refactoring.
The problem was, that detaching Node from parent does not remove it immediately, but parent keeps its reference to the next update, and call "hide" during this update.
The Sprites set on its display object Node a callback setting bbox to 0.0,0.0. When sprite was removed, the node with its callback persisted (as described in previous paragraph); If the new sprite was created in this same frame, it could receive same instance_id as the removed one, so the hide callback of the old Node set bbox of the _new_ sprite to 0.0, 0.0
=> Fix text selection

src/rust/ensogl/src/system/web/text_input.rs, src/rust/ensogl/src/system/web/text_input/text_input.js, src/rust/lib/frp/src/io/keyboard.rs
After pressing Alt-tab editor did not received keyup events so the keymask was stuck with pressed-alt state. To fix that, we clear the mask each time window lose focus.
=> Fix stuck keymask after alt-tabbing

src/rust/ensogl/src/display/shape/text/text_field/render.rs
Before blinking cursor was done by setting width to 0.0, but this leaves a very-thin line instead of disappearing cursor entirely.
This fixes this, and make the blinking by setting color to transparent instead of setting width.
=> Improve cursor blinking

src/rust/ensogl/src/display/shape/text/text_field/frp/keyboard.rs, src/rust/lib/frp/src/io/keyboard.rs
These are two fixes for pressing shortcuts in MacOS and Windows:
* in MacOS pressing key with CMD causes the keyup event to be missed
* on Windows pressing AltGraph also emits Control keydown.
=> Mac and Windows shortcuts fixes

src/rust/ensogl/src/display/symbol/gpu.rs, src/rust/ensogl/src/system/gpu/data/buffer.rs
This code was developed as a fix for occuring "crashes" on Windows, which were in fact a "contextLost" events of WebGl.
When we had Symbol without any instance created in it, we could get some empty buffers in instance scope. But the empty buffers were not marked as dirty on creation, so we didn't upload the "empty" data. Additionally, the method where we call the actual rendering assumed that there is always at least one instance. So it read one instance from uninitialized buffer, what left WebGl in some undefined state.
=> Fix drawing instance with empty buffers

src/rust/lib/macro-utils/src/lib.rs, src/rust/lib/shapely/impl/tests/derive_clone_ref.rs, src/rust/lib/shapely/macros/src/derive_clone_ref.rs, src/rust/lib/shapely/macros/src/lib.rs
`CloneRef` can be derived now. The macro allows for customizing bounds on the generated trait implementation. 
Still should add a few more tests to check that generated impls are sensible.
=> Proc macro for #[derive(CloneRef)]

src/rust/ide/src/executor/global.rs, src/rust/ide/src/model/module.rs
It fixes the tests which were failing in non-deterministic way.
Global spawner was made thread local
=> Fix problems with tests run in parallel

src/rust/lib/macro-utils/src/lib.rs, src/rust/lib/shapely/impl/tests/derive_clone_ref.rs, src/rust/lib/shapely/macros/src/derive_clone_ref.rs
Fix for issue reported by @wdanilo  that macro deriving CloneRef fails when target type declaration has bounds on its generic parameters or a where clause.
=> #[derive(CloneRef)] also works on types with type-level bounds.

src/rust/ensogl/src/display/render/composer.rs, src/rust/ensogl/src/display/render/passes/symbols.rs, src/rust/ensogl/src/display/render/pipeline.rs, src/rust/ensogl/src/display/scene.rs, src/rust/ensogl/src/display/shape/primitive/glsl/fragment_runner.glsl, src/rust/ensogl/src/display/shape/primitive/glsl/math.glsl, src/rust/ensogl/src/display/shape/primitive/system.rs, src/rust/ensogl/src/display/shape/text/glyph/system.rs, src/rust/ensogl/src/display/symbol/gpu.rs, src/rust/ensogl/src/display/symbol/gpu/geometry/compound/sprite.rs, src/rust/ensogl/src/display/world.rs, src/rust/ensogl/src/system/gpu/data/texture/class.rs, src/rust/ensogl/src/system/gpu/data/texture/storage/gpu_only.rs, src/rust/ensogl/src/system/gpu/data/texture/storage/remote_image.rs, src/rust/ensogl/src/system/gpu/data/texture/types/relations.rs, src/rust/ensogl/src/system/gpu/data/uniform.rs, src/rust/lib/graph-editor/src/component/node.rs, src/rust/lib/system/web/src/lib.rs
This PR addresses issue #317 by changing the texture format of symbol IDs to `Rgba32f`. This enables correct selections of nodes close to each other.
This also seems to resolve #331 .
This PR adds a requirement for the WebGL extension `EXT_color_buffer_float` to allow us the use of a float buffer.
This PR adds a new API to specify parameters for textures, which is required to set non-default parameters for the float texture.
As opposed to the requirements in isssue #317 this PR does not implement bit-reinterpretation between floats and integers, as these can lead to[ unexpected issues with `NaN`s](https://doc.rust-lang.org/1.19.0/std/primitive.f64.html#method.from_bits), which might lead to unexpected issues down the line. Instead, the numbers are cast between the datatypes.
Please …
=> Enable alpha blending for ID pass

src/rust/Cargo.lock, src/rust/ide/Cargo.toml, src/rust/ide/ast/impl/src/crumbs.rs, src/rust/ide/ast/impl/src/lib.rs, src/rust/ide/ast/impl/src/opr.rs, src/rust/ide/span-tree/src/action.rs, src/rust/ide/span-tree/src/iter.rs, src/rust/ide/span-tree/src/lib.rs, src/rust/ide/span-tree/src/node.rs, src/rust/ide/src/controller/graph.rs, src/rust/ide/src/double_representation/alias_analysis.rs, src/rust/ide/src/double_representation/alias_analysis/test_utils.rs, src/rust/ide/src/double_representation/connection.rs, src/rust/ide/src/double_representation/definition.rs, src/rust/ide/src/double_representation/graph.rs, src/rust/ide/src/double_representation/node.rs
This introduces operations on connections to the graph controller. This required additionally to implement searching for free variable name and changing expression node (like `2+2`) to assignment nodes (like `sum = 2 + 2`).
* Due to harsh timelines, there are some functions which needs to be refactored and does not conform to coding guidelines. That will be fixed in one of the next PRs.
=> Double Representation Connection operations

src/rust/ide/ast/impl/src/crumbs.rs, src/rust/ide/ast/impl/src/lib.rs, src/rust/ide/span-tree/src/action.rs, src/rust/ide/span-tree/src/generate.rs, src/rust/ide/span-tree/src/generate/macros.rs, src/rust/ide/span-tree/src/iter.rs, src/rust/ide/span-tree/src/node.rs
Before during SpanTree generation we treated macros as a leaves. Now we properly look into them, get all the AST nodes in their patterns and generate children of these SpanTree nodes from them.
- Segments' heads are not a SpanTree node.
- There is no possiblity to add or remove children of SpanTree node bound to macro.
=> Generating SpanTree from macros

src/rust/ide/enso-protocol/src/language_server/connection.rs, src/rust/ide/enso-protocol/src/language_server/tests.rs, src/rust/ide/enso-protocol/src/project_manager.rs, src/rust/ide/json-rpc/src/handler.rs, src/rust/ide/json-rpc/src/macros.rs, src/rust/ide/src/controller/module.rs, src/rust/ide/src/controller/text.rs, src/rust/ide/src/lib.rs, src/rust/ide/src/model/synchronized/execution_context.rs, src/rust/ide/tests/language_server.rs, src/rust/ide/tests/project_manager.rs
This PR introduces zero-copy JSON-RPC methods wherever it's possible.
* Every parameter is translated as references so we don't need to move ownership.
* It's also true for copy types such as atomic types.
=> Zero-copy JSON-RPC methods

src/rust/lib/logger/src/lib.rs
In my previous PR I mistakenly merged the version with logs enabled. 
Logs that shouldn't be enabled, until we implement #444 — they slow us down way too much.
This reverts this change.
=> Removed logs that I've accidentally enabled

src/rust/ide/enso-protocol/src/binary/client.rs, src/rust/ide/enso-protocol/src/language_server/tests.rs, src/rust/ide/enso-protocol/src/lib.rs, src/rust/ide/enso-protocol/src/project_manager.rs, src/rust/ide/json-rpc/src/lib.rs, src/rust/ide/json-rpc/tests/test.rs, src/rust/ide/utils/src/test.rs, src/rust/ide/utils/src/test/future.rs, src/rust/ide/utils/src/test/stream.rs
This PR refactors the functions to test Futures and Streams into extension traits for nicer syntax. Also added a few more and improved documentation.
=> Refactored utilities for testing Futures and Streams

.github/CODEOWNERS
I'll be off for the next two weeks, therefore I change the owner of IDE to Michał, so IDE PR-s won't be blocked.
=> Change IDE owner to mwu-two

src/rust/ensogl/src/display/shape/text/text_field.rs, src/rust/ensogl/src/display/shape/text/text_field/render.rs, src/rust/ensogl/src/display/shape/text/text_field/render/assignment.rs, src/rust/ide/src/view/text_editor.rs
This is a hotfix for a half of the bug with resizing IDE. 
Before the TextField component did not support resizing. The proper way to implement it got stuck, and later there were more importand things to do. However, the issue with resizing IDE must be fixed somehow.
The issues for make textfield properly are #177 #178.
=> Hotfix for TextField resizing

src/rust/lib/graph-editor/src/component/node.rs, src/rust/lib/graph-editor/src/component/visualization/container.rs, src/rust/lib/graph-editor/src/component/visualization/registry.rs, src/rust/lib/graph-editor/src/component/visualization/renderer/example/native.rs, src/rust/lib/graph-editor/src/lib.rs
Adds three new FRP endpoints to the graph editor:
* `visualization_enabled  : Stream<NodeId>`
* `visualization_disabled : Stream<NodeId>`
* `set_visualization_data : Source<(NodeId,Data)>` 
=> Extend graph editor api to allow data to be set on visualizations and stream the visibility status of visualisations.

src/rust/ensogl/src/control/io/mouse.rs
Use the up to date scene shape data to calculate mouse event positions.
The previous version would move the actual shape data of the scene (`shape`) on initialization into the closure that instantiates mouse events. From then on all mouse events were initialized with this data and their positions calculated based on this data. When the scene size changed, this would go out of sync with the actual scene shape and the position of our mouse cursor would no longer align with the actual position of the system cursor.
The fix is to move a handle into the closure that allows access to the up-to-date scene shape data at any time instead of the actual data.
=> Fix: Mouse cursor has wrong position after scene resize. 

src/rust/ensogl/src/display/shape/text/text_field/content.rs, src/rust/lib/data/src/text.rs
There are two ways to change the conent of the text field: either applying edits or using `set_content` method to replace it totally.
The latter lacked proper invalidation for the `line_offsets`, leading to invalid index recalculations later.
=> Correctly invalidate line offsets after setting the text field's content

src/rust/ide/parser/build.rs, src/rust/ide/parser/tests/id_map.rs
This PR:
* bumps the parser version so the issue with id mapping when there is an empty line in block is fixed ( https://github.com/luna/enso/pull/808 );
* enables test for id map handling and adds more case to cover the parser's fix;
* adds proper error handling in the build.rs — we may get a reply but this reply may contain an error which was previously not recognized.
=> Bump parser to fix metadata loss on entering a newline

src/rust/lib/graph-editor/src/component/node/port/output.rs
Adds a delay to the visibility onset on ports. This avoids the blinking of ports during mouse movements over nodes that are not intended to interact with the node.
* hack: there are some invalid mouse events on startup that would leave the ports visible by default. This is compensated for by manually hiding the ports, even though this would otherwise b the default state.
=>  Delayed appearance of multi ports

.github/workflows/build.yml, .github/workflows/check.yml, run, src/rust/ensogl/src/display/shape/text/text_field/frp/keyboard.rs, src/rust/ide/src/view/text_editor.rs, src/rust/lib/frp/src/io/keyboard.rs
This PR fixes an issue on MacOS which kept text field typing when using `command` modifier key.
* Platform::query() was used to deal with OS intricacies.
=> Fixed textfield key masking on Mac

build/run.js, src/rust/lib/graph-editor/src/component/cursor.rs, src/rust/lib/graph-editor/src/component/edge.rs, src/rust/lib/graph-editor/src/component/node.rs, src/rust/lib/graph-editor/src/lib.rs
Adds the ability to start connections from input ports.
Known issues:
* It is possible to start multiple connections from input and output ports. This will be addressed with #592
* On start dragging from an input port, the edge shape is not in the most aesthetically pleasing shape. (the cursor tries to select the port and the edge loops back)
=> Connect nodes starting from input ports.

build/run.js, src/rust/ensogl/src/display/shape/primitive/def/class.rs, src/rust/ensogl/src/display/shape/primitive/def/modifier.rs, src/rust/ensogl/src/display/shape/primitive/def/var.rs, src/rust/ensogl/src/display/shape/primitive/glsl/shape.glsl, src/rust/ensogl/src/display/shape/primitive/shader/canvas.rs, src/rust/lib/graph-editor/src/component/node.rs, src/rust/lib/graph-editor/src/component/node/port.rs, src/rust/lib/graph-editor/src/component/node/port/output.rs, src/rust/lib/graph-editor/src/lib.rs
Adds multiple output ports to nodes that are highlighted on hover.
* hack: there is not yet a good way to manage the order of shapes. To compensate for this a method that initializes the shapes is provided and called at the right place to ensure the correct order of shapes. The correct management needs to be still implemented once shape order management is available.
=> Implement segmented output ports.

src/rust/lib/graph-editor/src/lib.rs
As confirmed with @wdanilo previous change Ctrl-Space => Space was not intentional.
We want this shortcut to use Control, because otherwise text editor accepts space as text input.
=> Change visualization toggle shortcut to Ctrl+Space

src/rust/ensogl/src/display/shape/primitive/glsl/shape.glsl
Adds the adjustment of the bounds for the SDF `grow` modifier.
=> Enable computation of SDF bounds for `grow` modifier.

build/run.js, src/rust/ide/ast/impl/src/lib.rs, src/rust/ide/ast/impl/src/opr.rs, src/rust/ide/ast/impl/src/prefix.rs, src/rust/ide/parser/src/lib.rs, src/rust/ide/parser/tests/ast.rs, src/rust/ide/span-tree/src/action.rs, src/rust/ide/span-tree/src/builder.rs, src/rust/ide/span-tree/src/generate.rs, src/rust/ide/span-tree/src/lib.rs, src/rust/ide/span-tree/src/node.rs
This is a part of #545: The optional Expression Id was added to SpanTree, to allow reading type information by views.
Due to nature of opr::Chain and prefix::Chain, I decided to not put ast reference to SpanTree node yet. But the current design needs discussion, because it is sometimes troublesome.
=> Expression id in span tree

docs/shortcuts.md, src/rust/ide/src/view/node_editor.rs, src/rust/lib/graph-editor/src/lib.rs
This PR starts work on entering the nodes in the graph editor by adding the shortcut for triggering this action.
Currently the editor integration layer only logs the event, as the controllers logic is not yet present but it will allow testing controllers during the development in the live IDE environment,
=> The last selected node may be entered by pressing Ctrl+Enter.

src/rust/ide/src/view/node_editor.rs
As previously discussed, `refresh` is a better term and will help avoid any confusion with other meaning that `update*` functions commonly have in ensogl codebase.
=> Refactor update -> refresh in the graph editor integration

src/rust/lib/graph-editor/src/lib.rs
Reverts enso-org/ide#627 because of https://github.com/enso-org/ide/issues/631
=> Revert "Use correct cursor position for node dragging and node instantiation"

src/rust/ensogl/lib/text/src/typeface/font.rs, src/rust/ensogl/lib/text/src/typeface/pen.rs, src/rust/ensogl/src/display/shape/text/glyph/font.rs, src/rust/ide/src/model/synchronized/execution_context.rs
The `detaching_all_visualizations` test is shaky and fails 50%. It shall be skipped until it is properly fixed.
The fix is tracked by #637.
Along the way a few random warnings that appeared recently were fixed.
=> Disabled shaky test, fixed a few recently introduced unused import warnings

src/rust/ide/src/double_representation/graph.rs
Adding node at the end of the graph will prefer placing it after the last non-empty line rather than at very end (i.e. after blank lines). This addresses #641.
=> Proper Handling Blank Lines When Adding Node

docs/CONTRIBUTING.md, src/rust/ide/lib/enso-protocol/build.rs
This PR addresses #624 where engine developers get compilation errors when they try to build IDE without altering their setup.
This makes `flatc` run strictly opt-in, so the IDE will build correctly out-of-the-box.
Future improvements to the situation shall be tracked in https://github.com/enso-org/ide/issues/644
=> The `flatc` usage shall be guarded by environment variable

src/rust/ide/src/view/layout.rs, src/rust/ide/src/view/node_editor.rs, src/rust/ide/src/view/node_searcher.rs
Rather than passing node editor and graph controller separately to the node searcher, the searcher will be able to access node editor's controller directly.
Thanks to that, when node editor changes the displayed graph (e.g. due to entering a node), the searcher's copy of controller won't end up dangling.
This addresses #634
=> Searcher uses node editor's controller to add nodes

src/rust/ide/lib/ast/impl/src/crumbs.rs, src/rust/ide/lib/ast/impl/src/lib.rs, src/rust/ide/src/double_representation/module.rs, src/rust/ide/src/double_representation/text.rs, src/rust/lib/data/src/text.rs
Adds utilities to check the position of AST nodes in the text relative to their parents.
Also, fixed a number of byte/codepoint indexing mismatches and added some tests for this (though still coverage could be improved).
`impl std::ops::Index<Span> for str ` still needs more refactoring, will finish this tomorrow.
=> Obtaining child AST text span

build/run.js, src/rust/ide/lib/enso-protocol/src/language_server.rs, src/rust/ide/src/controller/graph.rs, src/rust/ide/src/controller/graph/executed.rs, src/rust/ide/src/controller/searcher.rs, src/rust/ide/src/executor/test_utils.rs, src/rust/ide/src/lib.rs, src/rust/ide/src/model/execution_context/plain.rs, src/rust/ide/src/model/module.rs, src/rust/ide/src/model/project.rs, src/rust/ide/src/test.rs, src/rust/ide/src/view/node_editor.rs, src/rust/ide/src/view/node_searcher.rs, src/rust/lib/data/src/text.rs
This PR adds access to the executed graph to the searcher controller. This will be used by a few different tasks, like #611 or #609. 
=> Searcher Controller has access to Executed Graph

src/rust/ide/lib/parser/src/jsclient.rs, src/rust/ide/lib/parser/src/lib.rs, src/rust/ide/lib/parser/src/wsclient.rs, src/rust/ide/src/model/suggestion_database.rs
closes #682 
Finally, the Documentation Parser and Generator is used somewhere (Yayyy 🎉 🎉 🎉 )
Modifies docstring from suggestion database to HTML code, enabling us to present documentation for nodes in searcher
=> Generate HTML Documentation in Suggestion Entries

build/run.js, src/rust/ide/lib/ast/impl/src/lib.rs, src/rust/ide/lib/ast/impl/src/repr.rs, src/rust/ide/lib/parser/tests/parsing.rs
This PR updates spaceless ast shapes to follow current scala implementation.
This prevents IDE from breaking when trying to deserialize them.
Everything is quasi-provisional, as the parser rewrite is underway.
Still, typing `[1,2,3]` shouldn't break double representation.
=> AST update

src/rust/ide/lib/view/src/graph_editor.rs, src/rust/ide/lib/view/src/graph_editor/component/node/port/output.rs
This PR fixes some small issues that appeared after merging the colored-tupes PR.
Three issues are fixed: 
- Output ports where showing one more output port than thy should
- Hovering from one output port to another did not correctly switch the output port
- A minor visual bugfix for updating the color of the cursor when hovering over ports. 
=> Fix Minor Bugs with Output Ports

src/rust/ide/lib/view/src/graph_editor.rs, src/rust/ide/lib/view/src/graph_editor/component/visualization/container.rs
Fixes a bug that leads to the visualization container no longer appearing when toggled through the keyboard shortcut.
Changes the `is_visible` method from the `visualization::Container` to `is_active` to avoid name collision with the `display::object::is_active` method.
=> Fix visualisation cotnainer not appearing on keyboard input.

.github/CODEOWNERS
As I and @wdanilo will be off for the next two weeks, @mwu-tow become the owner of our codebase for that period.
=> Set codeowners to mwu

src/js/lib/client/src/index.js
Reenables `.strict()` for yargs parser after macOS Big Sur fix.
=> Reenable `.strict()` for yargs parser after macOS Big Sur fix.

src/rust/ensogl/lib/theme/src/lib.rs
In some review fixes the text on searcher turn white.
=> Fix white text on light background in searcher

src/rust/ide/src/controller/graph.rs, src/rust/ide/src/double_representation/definition.rs, src/rust/ide/src/double_representation/identifier.rs, src/rust/ide/src/double_representation/module.rs, src/rust/ide/src/model/module.rs, src/rust/ide/src/test.rs, src/rust/ide/src/view/project.rs
Currently IDE fails to load if `main` method definition in not present or if it uses the `here.main` syntax.
This PR fixes both:
1) method pointer lookup will correctly take into consideration the module name to resolve the `here` symbol (related engine issue: https://github.com/enso-org/enso/issues/1138 ) 
2) if the `main` method cannot be found during the startup, it will be created
Currently I am marking this PR as a draft, because there's one more missing piece — the standard `main` definition stub requires also explicit `Base` import.
To be discussed how to handle this.
=> Handling missing main method on startup and `here.main` syntax

docs/product/shortcuts.md, src/rust/ide/src/view/integration.rs, src/rust/ide/view/src/code_editor.rs, src/rust/ide/view/src/project.rs
1. There was a possibility to set cursor on hidden Code Editor
2. Restored save command on "Ctrl+S"
=> Fix bugs in new code editor

src/rust/ensogl/example/src/text_area.rs, src/rust/ensogl/lib/text/src/component/area.rs
After introducing new Text Editor the selection symbol went to main view, and now it's covered by nodes.
=> Fix invisible cursor on nodes

src/rust/ide/lib/span-tree/src/action.rs
There was a wrong behavior when connecting to "labeled" argument in expressions being an infix, for example call `Main.foo`. Additionally fixed some issues with AST id change after such operation.
=> Fix ExpectedArgument handling in SpanTree

.github/workflows/build.yml, .github/workflows/check.yml, build/cmd.js, build/run.js, run
This fixes some manual workflow. Instead of defining LTS versions of `node` and `npm` in our run scripts, this downloads the information from NPM registry automatically. The only downside of this solution is that it adds approx `1s - 2s` to every `./run` command execution, which should not be a big deal, as we have the `watch` command which skips this check.
=> Bump npm node version

src/rust/ensogl/lib/core/src/display/world.rs, src/rust/ide/view/graph-editor/src/component/node/action_bar.rs
Make the hover area around node actions tighter to the actual buttons.
Re-enables debug shape visualisation shortcuts
=> PR: Fix node action bar hover area beeing too large.

src/rust/lib/frp/src/lib.rs, src/rust/lib/frp/src/nodes.rs
Adds a `filter` node and a `filter_map` node to the FRP library as requested in issue #813.
=> Add `filter` and `filter_map` nodes to the FRP library

src/rust/ide/lib/span-tree/src/generate/macros.rs
The subpatterns of Seq were traversed backwards.
=> Fix traversing Seq pattern

docs/product/shortcuts.md, src/rust/ide/lib/span-tree/src/generate.rs, src/rust/ide/src/tests.rs, src/rust/ide/view/graph-editor/src/lib.rs
Before if we received MethodCall about operator we always added ExpectedArgument InsertionType to SpanTree.
=> Fix ExpectedArguments SpanTree Nodes in Infix

src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/mapView.js, src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/scatterPlot.js, src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/tableView.js
As @sylwiabr found out today, table view didn't work on Tram's playground, and that was because visualization was trying to parse an already parsed object with Enso's builtin parser. Fixes the fact and also fixes it on other two visualizations.
=> Fixes visualizations when using Enso's builtin JSON parser

src/rust/ide/view/graph-editor/src/lib.rs
When pressing `enter` nodes area created at the wrong position (and the searcher appears at the wrong node position).
This PR fixes that by using the correct position for node creation. 
=> Create new nodes at the correct position.

src/rust/ide/src/view/integration.rs, src/rust/ide/view/graph-editor/src/lib.rs, src/rust/ide/view/src/project.rs
Before searcher brought by pressing Tab was always displayed under the mouse pointer. Now, if there are nodes selected, it will go under the selected node instead. Additionally, the newly created node is always selected.
There is also a fix for aborting adding/editing node.
=> Display Searcher under selected nodes

src/js/lib/content/src/index.html, src/rust/ide/view/graph-editor/src/builtin/visualization/native/raw_text.rs, src/rust/ide/view/graph-editor/src/component/visualization/container.rs, src/rust/ide/view/graph-editor/src/component/visualization/foreign/java_script/instance.rs
Avoids overlapping JS visualizations adding a background.
This fixes some occlusion issues.
This in only a partial solution to #867, proper solution requires #913 to be finalized and implemented.
=> Add background to js visualisation.

src/rust/ide/view/graph-editor/src/component/breadcrumbs.rs, src/rust/ide/view/graph-editor/src/component/breadcrumbs/project_name.rs
The FRP from the `Breadcrumbs` was incorrectly connected to the FRP of the `ProjectName` and updates were not propagated correctly. This PR fixes that. It also ensures an uninitialised project name (which should never happen) is more visible by changing the default text to something more obvious. 
=> Correctly propagate project name updates from `Breadcrumbs` to `ProjectName`.

src/rust/ide/view/graph-editor/src/component/visualization/container.rs
Avoids the background of the visualization container showing up when a new node is created on startup and when collapsing nodes.
This is not a great solution. It fixes the symptom but it does probably not address the root cause of this issue. I'm not sure what exactly the root cause is, but I suspect some parenting issue. Unfortunately, I have not yet been able to pinpoint a specific fix or reproducible bug regarding the order of parenting of all the shapes involved.  
Maybe this might even be involved to #761?  (I don't see the behaviour there, but I see the empty container showing up instead)
=> Avoid the visualisation container background showing up when loading the scene or collapsing some nodes.

build/run.js, src/rust/ide/src/controller/searcher.rs, src/rust/ide/src/controller/searcher/suggestion.rs, src/rust/ide/src/model/suggestion_database.rs, src/rust/ide/src/view/integration.rs
Searcher by default put module name as this argument when picked module method. However the name sometimes clashes with existing identifier. This is especially problematic in Main module with function main defined.
To avoid most common problem, the searcher will put "here" keyword instead of module name if the function chosen is a current module's method.
=> Put here keyword instead of module name

src/rust/ide/view/graph-editor/src/component/breadcrumbs/project_name.rs
When calling `rename` we only updated the visible project name, not the internally stored last committed one. 
So on pressing `esc` after startup, the initial project name was still `""` and we reverted to that one. 
This PR fixes that by adding the missing `commit` call to the `rename` method.
=> Correclty set project name after `rename`.

src/rust/ide/view/graph-editor/src/lib.rs
Detached edges are not cleaned up when entering/exiting nodes. This PR fixes that. 
=> Clear detached edges when entering/exiting nodes.

src/rust/ide/view/src/project.rs
In Project View FRP network in initial state editing was neither aborted and not-aborted, what gave a strange results. For example: the first created node was not put into the module code.
=> Fix initial state of Project View

src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/mapView.js
Found one more issue : getColor was deprecated, so that's why scatterplot didn't want to work properly.
Previously GeoMaps used unsafe eval() method and was passed a JS object. Now enso types work and json strings.
Screens:
Here you can see a new scatterplot layer. notice how it doesnt define center or zoom on map, those values are computed from the points:
It can also simply show a point on map without any problem whatsoever:
And display highly customizable GeoMap:
Test enso file:
```hs
from Base import all
type GeoPoint latitude longitude
type ScatterplotLayer data=[]
type GeoMap latitude=Nothing longitude=Nothing zoom=5 controller=True layers=[]
main =
pt1 = GeoPoint 37.85 -122.451
pt2 = GeoPoint 37.86 -122.452
pt3 = GeoPoint 37.82 -122.453
pt4 = GeoPoint 37.84 -122.454
pt5 = GeoPoint …
```
=> Fix GeoMaps on Enso types or JSON data.

src/rust/ide/view/graph-editor/src/lib.rs
Deactivate project name editing on node editing to avoid the project name keeping focus when a node is edited.
Proper fix would be to use focus management from #822, which does not exist yet.
=> Deactivate project name editing on node editing.

src/rust/ensogl/lib/core/src/display/scene.rs, src/rust/ide/view/graph-editor/src/lib.rs
Enables double clicks on the background in the graph editor to emit a `node_exited` event. 
Also restrict double click to enter the hovered nodes, not the selected ones, this addresses issue  #959.
- Can't be tested without language server integration.
=> Allow double click on background to leave the current node.

src/rust/ide/src/controller/searcher.rs, src/rust/ide/src/controller/searcher/suggestion.rs, src/rust/ide/src/model/suggestion_database.rs, src/rust/ide/src/view/integration.rs
Before the selected node, which ought to be passed as "this" argument for the next added node, was added when user picked function suggestion, immediately to the searcher input.
This PR changes that behavior: now the function name only is put into input. When new node is commited, then the this argument will be applied - even if user will not have picked any suggestion.
=> Apply selected node as "this" in all cases.

build/run.js, src/rust/ide/view/graph-editor/src/component/breadcrumbs.rs, src/rust/ide/view/graph-editor/src/component/breadcrumbs/project_name.rs, src/rust/ide/view/graph-editor/src/lib.rs
Removes the ability to edit the project name with a single click. Instead, the project name can now be made editable by `double press` or `cmd+click`.  Also, the cursor appearance is adjusted accordingly: cmd+hover shows an I-bar. 
=> Enable editing the project name only on `cmd+lmb` and `double press`.

build/run.js, src/rust/Cargo.toml, src/rust/ide/lib/span-tree/src/generate.rs, src/rust/ide/lib/span-tree/src/node.rs, src/rust/ide/src/controller/graph.rs
Introducing "labeled ports" and insertion points for expected arguments changes some Span-tree assertions we have in mind when implementing "finding by AST crumbs". This caused graph controller miss some connections in connection list - those were treated as "unconvertable" to span-tree crumbs.
Applied hotfix, and left TODO to consider how to do it better.
=> Fix missing connection in some cases.

src/rust/ide/view/graph-editor/src/builtin/visualization/java_script.rs, src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/geoMap.js, src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/mapView.js
Follows up on #977.
Cleans up the initialization of the maps visualization to use a basic initialization once, and updates later on.
Also introduces unique ids to allow multiple maps.
=> Allow multiple maps and re-use deck instances on data updates. 

src/rust/ide/view/graph-editor/src/builtin/visualization/java_script.rs, src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/scatterPlot.js, src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/table.js, src/rust/ide/view/graph-editor/src/component/visualization/registry.rs
1. Disables demo bubble visualization
2. TableView -> Table
3. replaced mapView to GeoMap, consistency(!)
4. Removed `(JS)` from Scatterplot label
=> Quicktake: Disable demo visualization, refactor names, remove '(JS)' from label.

src/rust/ide/src/view/integration.rs, src/rust/ide/view/graph-editor/src/lib.rs, src/rust/ide/view/src/debug_scenes/interface.rs
Fixes the port coloring: before we checked the expression id for being a node id, omitting all sub-expressions. Now we remember what subexpression id belongs to what node view and inform about types of all.
Coloring connections however still does not work. This pr includes a change in interface debug scene to show the problem: edges don't react for their endpoints' types changes.
=> This Simple Trick Will Enable Coloring of Your Ports!

build/run.js, src/rust/ensogl/lib/core/src/display/navigation/navigator.rs, src/rust/ensogl/lib/core/src/display/navigation/navigator/events.rs, src/rust/ide/view/graph-editor/src/lib.rs, src/rust/ide/view/src/documentation.rs, src/rust/ide/view/src/project.rs, src/rust/ide/view/src/searcher.rs
This changes the event handling behaviour when using the mouse wheel. Right now we prevent all default events, but this prevents also some [html components from receiving events](https://github.com/enso-org/ide/issues/939). Allowing default events while zooming with CTRL key, will lead to bad behaviour: the browser will do its website zooming and our UI will also zoom. We want to avoid the website zooming, but we do want to allow panning events to be received by scrollable html components.
To achieve this, this PR allows default events when a mouse wheel event is a pan event, but keeps it deactivated when there is a zoom event on CTRL + mouse wheel. 
=> Only prevent default zooming when holding ctrl key.

src/rust/ide/view/graph-editor/src/component/breadcrumbs/project_name.rs
Avoids setting focus for the text field of the project name when it is set "selected", that is, when it is the current active breadcrumb level. 
Adds some docs to clarify what "selected" in the API means. This was misleading before. 
=> Avoid changing edit status of project name when selecting it

src/rust/ide/src/controller/graph.rs, src/rust/ide/src/controller/graph/executed.rs, src/rust/ide/src/view/integration.rs
Adds a new update notification in the controller part, that indicates that the node expressions of a graph should be updated, but not the node positions.
=> Avoid updating positions of nodes during type updates.

src/rust/ide/src/view/integration.rs
Fix an issue when the connections were bound to old ports.
=> fix: Update edges on node expression updates.

src/js/lib/client/package.js
This PR removes block map generation when building the electron package. According to our source code comment:
```
// Disables "block map" generation during electron building. Block maps 
// can be used for incremental package update on client-side. However,
// their generation can take long time (even 30 mins), so we removed it
// for now. Moreover, we may probably never need them, as our updates
// are handled by us. More info: 
// https://github.com/electron-userland/electron-builder/issues/2851
// https://github.com/electron-userland/electron-builder/issues/2900
```
=> Remove blockmap generation when building electron package.

README.md
Make it point to something useful for newbie users like me.
=> doc: fix "documentation" link

.github/ISSUE_TEMPLATE/bug-report.md
I would highly recommend that you modify the bug report template, such that it doesn't have "description" first and "steps to reproduce" below, but just immediately start from "steps to reproduce"; see e.g. https://github.com/golang/go/blob/master/.github/ISSUE_TEMPLATE (from which I blatantly copied some parts; using good sources is a virtue).
The problem is, when a template starts with "description", I (a reporter) start filling it with freeform and somewhat chaotic, unstructured words basically describing the problem and maybe how I came to it; but then I have to repeat most of this work in "steps to reproduce" which is annoying and discouraging.
On the other hand, starting immediately from "steps to reproduce" (in the Go issue template: "What did you do?", which is a bit more open) …
=> chore: make bug template give better reports

docs/product/shortcuts.md
A backslash in markdown works as escaping char, so to emit a real backslash (in ctrl-\ keyboard shortcut), a double-backslash needs to be used.
=> docs: fix backslash working as escape char
